#define ENABLE_TEXTURE_COLOR false
#define ENABLE_UNDISTORT false
#define USE_ADAPTIVE_THRESH false
#define USE_LOCAL_THRESH false

#define USE_FEEDBACK_THRESH false

#define NUM_CALIBRATION_SAMPLES 4
#define USE_CALCULATED_CAMERA_MATRIX true


#define VERSION_STRING "0.01";


#define HTC_SENSATION_CAMERA_IMAGE_WIDTH 800
#define HTC_SENSATION_CAMERA_IMAGE_HEIGHT 480

#define NEXUS_S_CAMERA_IMAGE_WIDTH 720
#define NEXUS_S_CAMERA_IMAGE_HEIGHT 480


//Uncomment for use with Nexus S
//#define IS_NEXUS_S
#ifdef IS_NEXUS_S
	#define CAMERA_IMAGE_WIDTH NEXUS_S_CAMERA_IMAGE_WIDTH
	#define CAMERA_IMAGE_HEIGHT NEXUS_S_CAMERA_IMAGE_HEIGHT
#endif

//Default camera properties are for HTC sensation
#define CAMERA_IMAGE_WIDTH HTC_SENSATION_CAMERA_IMAGE_WIDTH
#define CAMERA_IMAGE_HEIGHT HTC_SENSATION_CAMERA_IMAGE_HEIGHT

#define HTC_SENSATION_CAMERA_MATRIX {92.5, 0, 400, 0, 92.5, 240, 0, 0 ,1};

