#define ENABLE_TEXTURE_COLOR false
#define ENABLE_UNDISTORT false
#define USE_ADAPTIVE_THRESH false
#define USE_LOCAL_THRESH false


#define CAMERA_IMAGE_WIDTH 800
#define CAMERA_IMAGE_HEIGHT 480
#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 540

#define NUM_CALIBRATION_SAMPLES 4

#define VERSION_STRING "0.01";